Refactored location and list views on mobile
mapzy/mapzy pull request #89
Opened 2022-10-01 21:43 UTC by spencerldixon

Tackling issue #79 

- Reduces top padding on the list and location panels by moving the close button to absolute positioning so it's always present when scrolling too, but doesn't overlap text.
- Makes the button styles between the two panels consistent

Happy hacktober! 🎃

2022-10-02 10:46 UTC, sagzy approved these changes
Hey @spencerldixon, congrats on your first contribution to Mapzy! 🎉

The code changes look good. The UI has been improved on mobile, without harming the desktop version. Happy to merge this PR.

@shafy good for you, too?

2022-10-02 11:00 UTC, sagzy requested changes
Actually after playing a bit more with the UX/UI, I noticed these two elements that would need a follow-up commit:

- "List view" (cf. screenshot). Here I would not change the styles of the links, as it's a list view with possibly hundreds of locations and the "fat" buttons are too aggressive visually. Would keep them as text links, as before. Could you revert this part of the changes @spencerldixon? 

- Clicking on the "Delete" button is not functional on either the "List View" or the "Show Location". Does it behave similarly for you @spencerldixon?

2022-10-02 16:00 UTC, shafy commented
hey @spencerldixon thanks for the PR! Agree with your feedback @sagzy. Regarding the delete button, I think this might be a pre-existing issue (my fuck-up) since it's hardcorded as `disabled: true`. We should probably change this to `disabled: @map.sync_mode` or is it related to something else?

2022-10-03 14:12 UTC, spencerldixon commented
Ah! Ok I agree the text links instead of buttons work better here. I've reverted those now.

The button doesn't seem to work for me either, I could take a look at that but might be best to keep it separate and do it in another pr? Or let @shafy tackle that if you'd prefer. Up to you!

2022-10-03 20:27 UTC, sagzy commented
Thanks for the new commit @spencerldixon. I opened issue #90 to fix the deletion button separately, feel free to look into it if you'd like to tackle that as well. Will now merge this PR. Thank you for your contribution! :)

2022-10-03 20:28 UTC, sagzy approved these changes

2022-10-03 20:29 UTC, merged